[default]
extend-ignore-re = ["api_id", "api_hash"]

[default.extend-words]
tdlib = "tdlib"
tdjson = "tdjson"
eframe = "eframe"
egui = "egui"
glow = "glow"
gpui = "gpui"
wgpu = "wgpu"
winit = "winit"
zizmor = "zizmor"
prek = "prek"
